apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: apache 
spec:
  replicas: {{ .Values.replicaCount }}
  template:
      labels:
        app: apache 
    spec:
      containers:
        - name: apache
          image: "{{ .Values.deployment.image.image }}:{{ .Values.deployment.image.version }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP