apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-{{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }} 
    spec:
      containers:
        - name: apache
          image: "{{ .Values.deployment.image.image }}:{{ .Values.deployment.image.version }}"
          ports: 
{{- include "port" . | nindent 12 }}
            # - name: http
            #   containerPort: 80
            #   protocol: TCP